spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER}
      config:
        server-addr: ${NACOS_SERVER}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

hkd:
  jwt:
    secret: ${JWT_SECRET}

logging:
  level:
    root: WARN
    com.hkd.gateway: INFO
